package myJava;

import java.util.Scanner;

public class colorChessboard {

	/**
	 * @param args
	 * 
3
BWW
BBB
BWB
		MaxIndex: 0 & MaxNum: 3
		
		测试用例:
8
BBWWBBWW
BBWWBBWW
WWBBWWBB
WWBBWWBB
BBWWBBWW
BBWWBBWW
WWBBWWBB
WWBBWWBB
		
		对应输出应该为:
		
		2
		
		测试用例:
4
BWBW
BBWB
WWWB
BWWW
		
		对应输出应该为:
		
		3
		
46
BBWBBWWWBWBBBWBWBWBBBWBBBBBBWBBBWWBWBBWWBWBWBW
BWWBBWBWBWBBBBBWBBBWWWWWBWWWWWWBWWWWBWWBBBBWWB
BWBWWBWBBWBWBBBWWWBWWWBWBBWWBWBWWWBBWWWWWWBWWB
WWBBBBWBBWWBBWWWBWWWWWWWWBWWBBWWWWBWBBBBWWBBBW
BBWWBBWBWWBBBWWWBBWBWWWWBBBWBBBWWBWBBBWBWWBBWW
WWBWBWBWWWWBWBWWBBBWWBBWBBWWWBBBWWWBWWWWWWWBWW
WBBWWWWWBBBBWWBWWWBWWBWBWWBWWWBBBBWBBWBBWWBWBW
BBBBWWWWWWBWWBWWWBWBWBBBWBWWBWWBWWBWWBWBWBWWWW
BWBBBWWWWBWBWBWWBBWBWBBWBWBBBBWWBWBBWBBBWWWWWB
WBBWWWBBWBWBWBBWBBBWBWWBWBWWWWBBWBWWWBBWBBBBWB
WBWBBBBWBBWWWWBBBBBBWWBBWWBBWWWWBWWWBBWWBBBBWW
BWBBWWBWWBWWWBBWBWWBBWWWWBWBWBWWWWBWWWBWWWBBWW
WWWWWBWBBBWBWBBWBBBBWWBWWBWBBBBBWWWBBBWWWBWBWW
BWBWWWWBWBBWBWBWWWWWWBWBWWWWBWBWWBWBBWBWBBWBWB
WBBWWBWBWBBWBWWWBBBWBWWBBBBBWWBWWWWWBBBWWBBWBB
WBBWBBWBWWWBWBWWBWWBWWBBWWBBBBWBWWBWBWBWBWBWBW
WBWWWWBWWBWWBWBBWBBWBBWWWBWBBWBBWBWBWWWBWBWBBB
WBBWWWBBWWBWBWWWWWBWWBWWWWBWWBBWWWBWBBBBWWBBBW
BWBWWBBWWBWWWWBBBBWWWBBBBBBWBWBBWBWWBBBBBWBBBW
BBBBBWWBBWBBWBBBWBBBWWBWWBBWBBBWBWBWWWWBWBWBWW
WBBBWWBWWWBWBWBWBWBBBWWBWWBBWWWWWBWWBBWBWBWBWB
WWBBWWBWBWWWBWBBBWBBWBWBWWBWWBWWBBBBBWBWWBWBBB
BWWWBBBWWBWWBWWBBBWBBWBBBBWBWBBBWBWWWWWWBBBWWB
BBBWBWBBBWWBWBWBWWWWBBWBBWWWBWWBWBWWWWWWBWWWBB
WWWBBWWWWBBWWWBWWWWWBBBBBBWBBBWWBBBBWWWWWWBBBW
BBWBWBBBBBWBWWBWWWBBWWBBWBBBBBBWWWBWWBWBWWWWBW
WBWWWBWBBWBBWWWWBBWBWBBBBWBBBBWBWBBBWWBWWWWWBW
WBWBWBBBWBWWWBBWWWBBBBBBBWBWWWWBWWWWBBWWWWBWBW
WBBWWBBBBBBWWBBBBWWBWBBBBBWWWBBWWBBBBBWWWWBWBW
WBWBBWWWBWWWBWBWBBWWBWWBBWWWWBBBBWWWWWWWBBWBWW
BBBWWBWBBBBBWBWBWWWWBWWBWBWWBBWBWBBBBWWBWWBBWW
BBBWWWBBWBWBWBBWWBBWWWWBWBBBWWBWWWBBWBWBBBWBWB
WBWBBWWWBBBBWWBWWBWWWBWBWBWWWBBBWWBWWWWWWWWWBB
BBBBBWWBWBBWBBWBWWBBWWWBBWBWWWBWWBWWBBBBBWBBBB
BWWBBBWWBWWBWWBWWWBWWBBBBWBWWBBWBWBWWWWBBBWWWW
BBBWBWBWBBWWBWWBWBWBWBWBBBWBWBWWBBBWBBWBWWWBBW
BWBBWWBBWWWBWWBWWBBBWWWBBBBWWWBBWBBWBBBBWBBWWB
BWBWWWWWWBBBBWWBBWBBBBBBWBBWBWWWBWBBBWWWWWWBBB
WWBWWWBBWWBWWWBBWWWBWWBBBBWBWBBBWWWBBWWWBWBBWW
WWWBBWWBBBBWBWBWWWWBBBWBBBWWWWWBBWWBBBBWWBBBBB
BWWBWBBBWWBBWWBWWWBWWBBBWBBWBWBBBBWBWBWWWWBWBB
WWBWBWWBWWBWWBBWWBBBWBWBBBWBWWWBWWBBWWBBBWBWWB
BBBBWBBBBWBWBBBWBWBWBBBWBWBWBWWBBBBWBWWBBBBWBW
BBBBWBBWWBBBWBBBBWBBWBWWWBBBWBWWBWWWWWWBWBWWBW
BBWWBBBWBBWBWWWWWWBBBBWWWWWWWBBBBWWBWWBWWBWBWB
WWBBWWWBBWWBBBBWBBBBWWWWBWBBBBBBWBBBBBWWBWWWWW

	对应输出应该为:22
	 */
	static int MaxNum=0;//,MaxIndex=0;
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		int size = sc.nextInt();
		String temp = sc.nextLine();
		char[][] board = new char[size][size];
		int i,j;
		for(i=0;i<size;i++){
			board[i]=sc.nextLine().toCharArray();
//			System.out.println(board[i]);
		}
		int number=0;
		int jMax=0;		//保存连续的颜色
		for(j=0;j<size;j++){
			number=0;
			jMax=0;
			for(i=1;i<size;i++){
				if(board[i][j]==board[i-1][j]){
					number++;
//					jMax=number+1;
				}
				else{
					if(jMax<number+1){
						jMax=number+1;
					}
					number=0;
				}
				
			}
			if(jMax<number+1){
				jMax=number+1;
			}
			if(jMax==0){
				jMax=size;
			}
			if(jMax>MaxNum){
				MaxNum=jMax;
//				MaxIndex=j;
			}
		}
		
		
		System.out.println(MaxNum);
//		System.out.println("MaxIndex: "+MaxIndex+" & MaxNum: "+MaxNum);
	}

}
